### ISSUE TITLE
Request for custom file name for exported gpx/kml

### ISSUE THREAD

**Issue by damjang** [destil/GPS-Averaging#2]
Hi! I'm here because want to ask if possible to add a possibility to customize the filename of exported gpx/kml . I mean here to ask every time the filename to be used. By default can be like now the date/time, but better for date to use year_month_day instead day_month_year, to have better ordering by filename.
Also a setting to define if export gpx and kml, only gpx or only kml will be usefull.

Thank You

**Comment by destil** [comment]
Hi, you are welcome to send a pull request.

**Comment by destil** [comment]
File export has now been reworked - it's not saved to the SD card, but fired into a system. Then you can select app which can work with it, for example Save it to Google Drive, attach to e-mail etc.
