### ISSUE TITLE
Problem with ads removing

### ISSUE THREAD

**Issue by wkuranowski** [destil/GPS-Averaging#3]
Hi. I would like to pay and remove ads from your app, but it doesn't work. When I click on "Remove Ads & More", nothing happens.

I am using Samsung Galaxy S5 with stock Android Lollipop 5.0.

**Comment by destil** [comment]
Hi, I'm not planning further development of the app. You can submit a pull request though.

**Comment by destil** [comment]
I decided to continue development, just fixed it.
